### ISSUE TITLE
why not move table.Lock() into table.addInternal()?

### ISSUE THREAD

**Issue by yiyang5055** [muesli/cache2go#12]
```
func (table *CacheTable) Add(key interface{}, lifeSpan time.Duration, data interface{}) *CacheItem {
	item := NewCacheItem(key, lifeSpan, data)

	// Add item to cache.
	table.Lock()
	table.addInternal(item)

	return item
}
```
In general,Lock() and UnLock() is pair in function,why not move table.Lock() into table.addInternal()?Is there anything other to consider?

**Comment by muesli** [comment]
addInternal is used from multiple places where the table is already locked. For performance reasons we don't want to unlock & relock here.

**Comment by yiyang5055** [comment]
yeah, thank you very much!
