### ISSUE TITLE
Question about SetAddedItemCallback

### ISSUE THREAD

**Issue by NicholasLiuWei** [muesli/cache2go#33]
hello 
请看如下函数，是不是应该将这这段注释掉
func (table *CacheTable) SetAddedItemCallback(f func(*CacheItem)) {

	//if len(table.addedItem) > 0 {
	//	table.RemoveAddedItemCallbacks()
	//}
	table.Lock()
	defer table.Unlock()
	table.addedItem = append(table.addedItem, f)
}

**Comment by muesli** [comment]
Please be aware that we only speak English in this repo. From what I can gather, you're suggesting to remove the first three lines? What's the reasoning behind it?

**Comment by DoubleChuang** [comment]
> hello
> 请看如下函数，是不是应该将这这段注释掉
> func (table *CacheTable) SetAddedItemCallback(f func(*CacheItem)) {
> 
> ```
> //if len(table.addedItem) > 0 {
> //	table.RemoveAddedItemCallbacks()
> //}
> table.Lock()
> defer table.Unlock()
> table.addedItem = append(table.addedItem, f)
> ```
> 
> }

Because there is already an AddAddedItemCallback,
SetAddedItemCallback is used to replace the current call back function

因為SetAddedItemCallback 是用來取代 當下設定的 回調函式
如果把那三行註解了就跟AddAddedItemCallback函式一樣 是用來增加函式到回調函式列表

**Comment by muesli** [comment]
So I guess we can close this one.
