### ISSUE TITLE
May I ask why using the go rountine in the  time.AfterFunc, the param func should be run by an rountine

### ISSUE THREAD

**Issue by leoxu1719** [muesli/cache2go#44]
https://github.com/muesli/cache2go/blob/4098a3aa8c94da4e28e868b5be85c42ad8d59214/cachetable.go#L166

**Comment by leezhu** [comment]
yes, it run by an routine, so it will not block the main gorotine. another goroutine will be time.AfterFunc to run when this expirationCheck func done. you can understand one cacheTable have only one expireationcheck func grouting

**Comment by muesli** [comment]
I'm sorry but I don't fully understand the question. I hope @leezhu's response was helpful.
