### ISSUE TITLE
Support deploy in distribution environment？

### ISSUE THREAD

**Issue by wwhai** [muesli/cache2go#55]
Support deploy in distribution environment at current version？

**Comment by muesli** [comment]
I"m afraid I don't fully understand your question. Can you be a bit more specific what you're trying to do?

**Comment by wwhai** [comment]
> I"m afraid I don't fully understand your question. Can you be a bit more specific what you're trying to do?

I means Distributed Scene

**Comment by muesli** [comment]
What is a "Distributed Scene"?

**Comment by wwhai** [comment]
> What is a "Distributed Scene"?

![Uploading image.png…]()

**Comment by muesli** [comment]
No, that's not supported and probably out of scope. I'd probably check out https://github.com/golang/groupcache for that.
