### ISSUE TITLE
Maybe is problem with Less function although this function is unused.

### ISSUE THREAD

**Issue by spring410** [muesli/cache2go#8]
func (p CacheItemPairList) Less(i, j int) bool { return p[i].AccessCount > p[j].AccessCount }
#I think it should be:
return p[i].AccessCount < p[j].AccessCount

#Is that right?

**Comment by wenhao-fly** [comment]
go1.8？

**Comment by muesli** [comment]
It depends which way you want to sort slices. This is commonly used to sort the cache by most-accessed items, so this is correct.
